openapi: 3.0.0
info:
  title: Converter
  version: 1.0.0
servers:
  - url: http://localhost:4000
paths:
  /upload:
    post:
      tags:
        - default
      summary: Upload&Convert
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /upload/{filename}:
    get:
      tags:
        - default
      summary: Download Uploaded
      parameters:
        - name: filename
          in: path
          schema:
            type: string
          required: true
          description: filename
          example: 5d0583dd9a49ed1d5f87fecd20987a42-ScreenRecorderProject1.mp4
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
